version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.5  

    steps:
      - checkout 

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: RuboCop Lint
          command: rubocop --format simple --fail-level warning

      - run:
          name: Run RSpec tests
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build