version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9.0

    steps:
      - checkout  

      - run:
          name: Install dependencies
          command: |
            pip install unittest
            pip install pylint

      - run:
          name: Run unit tests
          command: |
            python -m unittest discover -s tests

      - run:
          name: Run pylint
          command: |
            pylint unit_test.py

workflows:
  version: 2
  build:
    jobs:
      - build
